// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, public_member_api_docs
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqFZ3AuBKb01i_5iUl7y2V18qT8xL7WrM',
    appId: '1:995350713039:web:6a8d83705adb5fe47dddba',
    messagingSenderId: '995350713039',
    projectId: 'sliderpuzzle-flutter',
    authDomain: 'sliderpuzzle-flutter.firebaseapp.com',
    storageBucket: 'sliderpuzzle-flutter.appspot.com',
    measurementId: 'G-X29Y8JPT7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8jRPrnTEFoDkZzxO3Wd311Bj8iRFORD0',
    appId: '1:995350713039:android:3ca530715a5e3f007dddba',
    messagingSenderId: '995350713039',
    projectId: 'sliderpuzzle-flutter',
    storageBucket: 'sliderpuzzle-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVcT5NlgcZH4uighxRnBIme_s4pDBWJZo',
    appId: '1:995350713039:ios:3a1d25cd024d01a57dddba',
    messagingSenderId: '995350713039',
    projectId: 'sliderpuzzle-flutter',
    storageBucket: 'sliderpuzzle-flutter.appspot.com',
    iosClientId: '995350713039-kjih0etrm82itu1a7rvitd2tq3pte5l3.apps.googleusercontent.com',
    iosBundleId: 'org.rozendallabs.sliderpuzzle-flutter',
  );
}
