name: leaders_api
description: The interface and models for an API providing leaderboard entries.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  meta: ^1.7.0
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
